### ISSUE TITLE
moold setup and removel form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#103]
![capture](https://cloud.githubusercontent.com/assets/11412673/7369603/d732db1e-ed78-11e4-8a8f-c29f681ad709.PNG)
Total hours not displayed

**Comment by nishant-njs** [comment]
See below screenshot. The "Total Hours" is missing in MS Access version. My designer accidentally added the field. Shall we remove "Total Hours"?

![screenshot](https://cloud.githubusercontent.com/assets/7536874/7370114/5b1b586e-edd5-11e4-9c0b-cb0c034bd3d1.jpg)

**Comment by nishant-njs** [comment]
We can remove "Total Hours" if you wish since it is not there in MS Access. Or, we can leave the field as it is - the hours will be calculated and displayed.

**Comment by philolsonjr** [comment]
ok
