### ISSUE TITLE
molding notification

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#104]
If a mold has a notification that is not turned off it must print with the setups for today report. See below:
![capture](https://cloud.githubusercontent.com/assets/11412673/7370231/39df3a0a-ed7e-11e4-913d-b465e37b6df7.PNG)

**Comment by nishant-njs** [comment]
1) To which button is the above function Command285_Click() associated (please provide screenshot from Access)?
2) Do both reports open simultaneously or are they combined in 1 report (please provide screenshot from Access)
3) Where is the function/filter where you check "If a mold has a notification that is not turned off it must print with the setups for today report." (please provide screenshot from Access)

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7459155/9186825a-f25f-11e4-830f-d734a754be83.PNG)
Print setups for today as shown above.

It print all setups and then prints all notifications.


 Where is the function/filter where you check "If a mold has a notification that is not turned off it must print with the setups for today report." (please provide screenshot from Access)????? I do not use filters so I do not know what you are looking for.

**Comment by philolsonjr** [comment]
Still not working

**Comment by nishant-njs** [comment]
I know. We haven't worked on this today.

**Comment by nishant-njs** [comment]
Updated. Molding Notification Report will be printed along with Print Mold Setup Sheet for Today.
![1](https://cloud.githubusercontent.com/assets/7536874/8082414/d4a76f56-0f9a-11e5-96c1-712024898067.jpg)

**Comment by philolsonjr** [comment]
No picture see below:
![capture](https://cloud.githubusercontent.com/assets/11412673/8115323/2ba24916-1040-11e5-87a8-6f101fff7142.PNG)

![capture](https://cloud.githubusercontent.com/assets/11412673/8115342/520412ba-1040-11e5-91f4-0fb6400bc4b6.PNG)

**Comment by nishant-njs** [comment]
Fixed. Please try again. We tested on the beta server - see screenshots.

![1](https://cloud.githubusercontent.com/assets/7536874/8129625/a4a243c8-1128-11e5-9890-1ed06b145e25.jpg)

![2](https://cloud.githubusercontent.com/assets/7536874/8129630/a9a649b4-1128-11e5-988a-50bd03fb4ebc.jpg)
