### ISSUE TITLE
Shop Floor - Web Browser and Version

### ISSUE THREAD

**Issue by nishant-njs** [nishant-njs/mold_maintenance_db#105]
Will the operator use Internet Explorer on the shop floor? What version is it currently running? (see below screenshots for guidance)

![1](https://cloud.githubusercontent.com/assets/7536874/7389602/34633c7e-ee8d-11e4-8a09-cee3ef1a3545.jpg)

![2](https://cloud.githubusercontent.com/assets/7536874/7389611/38256bb6-ee8d-11e4-96b8-30e83a5771d1.jpg)

**Comment by philolsonjr** [comment]
I can not answer this question.

**Comment by patakyp** [comment]
S&C Chicago is currently running IE9 (9.0.8112.16421).

**Comment by nishant-njs** [comment]
Noted. Thanks.
