### ISSUE TITLE
Mold removal form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#106]
![capture](https://cloud.githubusercontent.com/assets/11412673/7392464/88f8959e-ee4d-11e4-8531-e528f89334da.PNG)
Ok I cannot close the form because Mold start number cannot be 0.
I cannot enter a value so I stuck in a loop.
The setup form did not require a value and the form closed.

**Comment by nishant-njs** [comment]
Mold Start Number won't be 0 anymore. It is validated in previous step - "Mold Setup and Removal Form' as discussed over phone/email. Please test and close if resolved.
