### ISSUE TITLE
Schedule mold change

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#110]
![capture](https://cloud.githubusercontent.com/assets/11412673/7460670/6878cfde-f26a-11e4-9671-05d34643742a.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7460679/82bef936-f26a-11e4-98aa-71049a76a12f.PNG)
Mold preferred resource should load when a mold is selected from pull down list, see above.

**Comment by nishant-njs** [comment]
It is working as it should. In the web version of screenshot, you have selected a part number where in the ResourceIN value is 0. 
![screenshot](https://cloud.githubusercontent.com/assets/7536874/7467672/652b14de-f31b-11e4-8bd7-4d6dfaba9b07.jpg)

Similar situation in Access with same part number - 
![1](https://cloud.githubusercontent.com/assets/7536874/7467691/c382d2a6-f31b-11e4-93cf-94ba50c83f5b.jpg)

![2](https://cloud.githubusercontent.com/assets/7536874/7467692/c73c3388-f31b-11e4-94b8-59ee9b078a9a.jpg)

Please review.
