### ISSUE TITLE
Mold service Schedule report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#112]
Notes need to be displayed
![capture](https://cloud.githubusercontent.com/assets/11412673/7519223/61c5739e-f4a5-11e4-93ba-68eb1dac785d.PNG)
 on report.
![capture](https://cloud.githubusercontent.com/assets/11412673/7519202/523d6ce2-f4a5-11e4-98ce-9a34bbee28fd.PNG)

**Comment by nishant-njs** [comment]
Fixed. Please test and close the issue.
