### ISSUE TITLE
Mold service form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#113]
![capture](https://cloud.githubusercontent.com/assets/11412673/7519436/409a5968-f4a6-11e4-9607-8dff96e45080.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7519467/4f96a1ba-f4a6-11e4-9bf8-53c4ce32eaaf.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7519545/7c1b0276-f4a6-11e4-9343-1d17e3c0f77c.PNG)
Note missing on closing form.

**Comment by nishant-njs** [comment]
Fixed. Please test and close the issue.
