### ISSUE TITLE
Mold notification 

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#119]
Print setups for today report does not molding notification for part being set.
![capture1](https://cloud.githubusercontent.com/assets/11412673/7616694/1d1a0af4-f96c-11e4-83f9-6d61644489bb.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7616699/1f52eb60-f96c-11e4-9fde-f477672d22f4.PNG)

**Comment by nishant-njs** [comment]
Is this issue similar to Issue #104 ? If not, please elaborate. If yes, please close this issue. We will resolve #104 .
