### ISSUE TITLE
Move service request to tool room schedule

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#120]
![capture](https://cloud.githubusercontent.com/assets/11412673/7617114/c9d2c266-f96e-11e4-9fd5-d4b87412e082.PNG)

Move these to this???

![capture](https://cloud.githubusercontent.com/assets/11412673/7617132/e0faedce-f96e-11e4-8c16-dd0b7018dab4.PNG)

**Comment by nishant-njs** [comment]
Confusing. The two screenshots (reports) above works independently. Please elaborate what you mean by "Move service request to tool room schedule".

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7657984/0533f990-fafc-11e4-8c55-e557aa4eff3b.PNG)
Create mer button adds to tool shop report.

**Comment by nishant-njs** [comment]
We've got a question here:

When an operator creates a service request - he/she can chooses either from Mold Number, Core Number or Tool Number. 

![1](https://cloud.githubusercontent.com/assets/7536874/7678105/15044080-fd6f-11e4-92db-0eefc304efcb.jpg)

Say the operator selects only Mold Number. In which case, in Mer_Data it has only Tool number column. We found you are inserting Mold Number into the Tool number column which doesn't make sense.

![2](https://cloud.githubusercontent.com/assets/7536874/7678119/2c3512ac-fd6f-11e4-9e8d-e6a86c73872b.jpg)

Finally, referring to Mer_Data form above, where are you getting the following fields information from:
Division Name, Account Number Person to Notify, Urgent, Safety etc.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7689119/85576d9e-fd6f-11e4-80c0-aea4168a94c6.PNG)

**Comment by nishant-njs** [comment]
Create MER form is added now. Please test and close the issue.

**Comment by philolsonjr** [comment]
How to link to Tool Shop?????

**Comment by nishant-njs** [comment]
For now, MER_Data table is not linked to Tooling database. Paul Pataky will discuss this issue and few others in a day or two.

For now, you can verify below that a row is successfully inserted and displayed in the report.
![screenshot-1](https://cloud.githubusercontent.com/assets/7536874/7725743/017777a0-ff1b-11e4-8a08-2c1425d65ed5.jpg)

![screenshot-2](https://cloud.githubusercontent.com/assets/7536874/7725754/0c0e4464-ff1b-11e4-9600-cfb22b8322a9.jpg)
