### ISSUE TITLE
Mold to 

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#123]
Should be sorted by mold number.

![capture](https://cloud.githubusercontent.com/assets/11412673/7617446/b2a345aa-f970-11e4-8db9-802f2178850e.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7617463/d549e88e-f970-11e4-8bd2-463ff2ef21e9.PNG)

**Comment by nishant-njs** [comment]
Sorted. Please test and close the issue.
