### ISSUE TITLE
Create mold pm task

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#124]
select list has "asfd" why?

**Comment by nishant-njs** [comment]
This was added by my staff while testing. Record is deleted now. FYI - admin can add/edit/delete records.

![1](https://cloud.githubusercontent.com/assets/7536874/7648310/386f1f26-faff-11e4-8536-2091a1a3a7af.jpg)

![2](https://cloud.githubusercontent.com/assets/7536874/7648311/3ac54dfe-faff-11e4-97a7-aa2f8ac36a1f.jpg)
