### ISSUE TITLE
create request

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#128]
Pull down list is missing scheduled jobs review the displayed query.
![capture](https://cloud.githubusercontent.com/assets/11412673/7659568/80934954-fb08-11e4-970c-fcbe636bf716.PNG)

**Comment by nishant-njs** [comment]
Which form and pull down are you referring too? Please add screenshot.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7688965/6ec55e8e-fd6e-11e4-8b5b-3737add93178.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7688970/800924c8-fd6e-11e4-8dd1-072799f7496a.PNG)


All four jobs show be displayed on the report...


![capture](https://cloud.githubusercontent.com/assets/11412673/7689033/efdeb1c8-fd6e-11e4-9a6a-c79f8f0f54a6.PNG)

**Comment by nishant-njs** [comment]
Sorry but the screenshots are not helpful. We have verified our query (SQL) with MS Access. Can you share in detail with appropriate screenshots again explaining what's wrong?

As stated - "All four jobs show be displayed on the report" - we've verified the screenshots above with the data on beta server. The 4 records scheduled for May 18 are shown correctly.

**Comment by nishant-njs** [comment]
![1](https://cloud.githubusercontent.com/assets/7536874/7726629/f42824c2-ff20-11e4-8bed-5a134a9a54cd.jpg)

![2](https://cloud.githubusercontent.com/assets/7536874/7726632/f9c93984-ff20-11e4-96b9-8b74726e171a.jpg)
