### ISSUE TITLE
mold setup report 

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#129]
All molds removed from machines, three new setups completed, but one is displayed twice, it should not.
![capture](https://cloud.githubusercontent.com/assets/11412673/7659640/11e92464-fb09-11e4-930d-0c069eac9a09.PNG)

**Comment by nishant-njs** [comment]
This is resolved.  We have temporary added Order No in the report to distinguish records for our reference. We shall remove once the application is in production. The report at times display 2 rows similar to MS Access. See Issue No.: #19, Issue No.: #25 and Issue No.: #84.
