### ISSUE TITLE
Print setups for today not working again.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#131]
![capture](https://cloud.githubusercontent.com/assets/11412673/7659810/5e9e95f4-fb0a-11e4-9687-8268a0717edf.PNG)
 
![capture](https://cloud.githubusercontent.com/assets/11412673/7659841/9ae56146-fb0a-11e4-8101-d1ec50cd1742.PNG)

**Comment by nishant-njs** [comment]
When we deploy the code to the virtual server at S&C this should work. Currently, the server is located in India (different timezone) and therefore the difference. Refer Issue No.: #63

**Comment by philolsonjr** [comment]
Then we leave it open until tested.

**Comment by nishant-njs** [comment]
This issue can be tested and closed. Deployed the application and database to a virtual server at S&C. Should no longer have any timezone related issues.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/8166598/7034e6ee-135e-11e5-913e-58997401866f.PNG)

**Comment by nishant-njs** [comment]
The above screenshot is related to mold notification picture upload. See screenshot below. We've created a new issue #137 . This issue "Print setups for today not working again." is resolved. See our comment above "This issue can be tested and closed. Deployed the application and database to a virtual server at S&C. Should no longer have any timezone related issues."

![screenshot](https://cloud.githubusercontent.com/assets/7536874/8176303/99c95d56-1416-11e5-848c-f447c4eadc7f.jpg)

**Comment by philolsonjr** [comment]
Report is not correct. It prints the setup file, then both notification files, then the second setup file, then the two copies of the notifications. It should print all setup files and then all notification files. One copy each.

**Comment by nishant-njs** [comment]
Fixed. Please test.
