### ISSUE TITLE
Mold setup report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#132]
when a setup is complete a third line appears in the report.

![capture](https://cloud.githubusercontent.com/assets/11412673/7659931/735afc98-fb0b-11e4-8e6d-3db978364785.PNG)

**Comment by nishant-njs** [comment]
Fixed. Please test. This issue started occurring because we removed the criteria from "Mold Removed Date". See Issue No.: #87 . We have updated the query.
