### ISSUE TITLE
Schedule mold change

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#135]
Select current view should only display molds in a machine.
![capture](https://cloud.githubusercontent.com/assets/11412673/7660120/d764fbca-fb0c-11e4-829a-f429e45a02f2.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7660135/f2fec640-fb0c-11e4-9da7-5db0f89d2e7c.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7660148/0cd41fb6-fb0d-11e4-9a8c-6cde76d9f7f9.PNG)

**Comment by nishant-njs** [comment]
Fixed. Please test.
