### ISSUE TITLE
heater darta

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#136]
Must be able to view ALL heaters in form view to see note table as in access.

**Comment by nishant-njs** [comment]
Updated.
![1](https://cloud.githubusercontent.com/assets/7536874/8082337/1ca7b38e-0f9a-11e5-8b64-9ecfa28d153f.jpg)

**Comment by philolsonjr** [comment]
In access you roll the wheel on the mouse to page through the records in the table, this is what we need.

**Comment by philolsonjr** [comment]
You did not fix the problem, why assign it to me???
