### ISSUE TITLE
Report - Daily Mold Setup Schedule

### ISSUE THREAD

**Issue by nishant-njs** [nishant-njs/mold_maintenance_db#14]
Please let us know on what conditions the background color (columns: Machine State, Job Kitted) and Font color (columns: Mold Number, Shift, Date Schedule) changes to red, green or yellow.

**Comment by philolsonjr** [comment]
Machine state:
                              Red with time machine was ready
                              Yellow Setup complete by setup team
                              Green line leader has made a good part
Job kitted:
                              Green job has been kitted by the setup team
Mold number:
                              Red mold is dirty
                              Yellow mold can run
                              Green mold is clean and ready to go
Shift:
                              Blue shift 1
                              Red shift2
Date scheduled:
                              Red scheduled in the last 48 hours

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
