### ISSUE TITLE
display wrong file data type 

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#141]
![capture](https://cloud.githubusercontent.com/assets/11412673/11151125/f257b8b4-89f0-11e5-9104-c8b22a55b6b8.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11151896/2f9b3f30-89f5-11e5-9302-86f19bcc19cf.JPG)

**Comment by nishant-njs** [comment]
Fixed. Please mention "query name" when you create a new issue. This will help us know which query you are referring too.

**Comment by philolsonjr** [comment]
Note second screen shot shows query as 2015 Pareto chart???????
