### ISSUE TITLE
Reports have different data output

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#142]
![capture](https://cloud.githubusercontent.com/assets/11412673/11303502/c6fc4072-8f68-11e5-893c-cb9561c05159.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11303544/142bfb6c-8f69-11e5-9523-7790cefc4c09.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11303639/83ad1ed0-8f69-11e5-95de-3d055cac211d.JPG)

**Comment by nishant-njs** [comment]
1) I have requested in past and requesting again - please include the query name so we know the one you are referring too.

2) There are 3 screenshots. If we compare #2 and #3 - the results do match with MS Access except few digits after decimal in few records. We found that rounding works differently in MS Access and MySQL. But the number shouldn't make a difference.

3) In future, pease elaborate the issues in detail.

**Comment by philolsonjr** [comment]
Query name in screen shot. 
![capture](https://cloud.githubusercontent.com/assets/11412673/11632383/78cdec54-9ccc-11e5-9286-118634cf16a0.JPG)


Note number are now correct, so something was changed?
