### ISSUE TITLE
Review query many errors

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#144]
![capture](https://cloud.githubusercontent.com/assets/11412673/11309085/7ff6ff04-8f87-11e5-996e-9e18ffedeadf.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11309105/9275552c-8f87-11e5-8ca7-2f738bfdac0e.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11309119/a2772838-8f87-11e5-83ff-efda0146dfa2.JPG)

**Comment by nishant-njs** [comment]
Fixed. Try now. We found in MS Access that the Week starts from "1" while in MySQL "0".
