### ISSUE TITLE
Query values not correct.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#145]
![capture](https://cloud.githubusercontent.com/assets/11412673/11309238/49b4445a-8f88-11e5-80b9-cd8b9cdd8e68.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11309248/597f6ab8-8f88-11e5-8aca-b792e5100b09.JPG)

**Comment by nishant-njs** [comment]
The query is working correctly. Count the rows and compare the column values in Access and MySQL - they do match. For 1/5/2015 - 4 rows, 1/6/2015 - 6 rows, 1/7/2014 - 4 rows etc.
