### ISSUE TITLE
Report - Print Mold Setup Sheet for Today

### ISSUE THREAD

**Issue by nishant-njs** [nishant-njs/mold_maintenance_db#15]
1) Please let us know the conditions on which the font/background color changes for field: mold weight.
2) Also, there are few data shown in red - are they based on a condition?

**Comment by philolsonjr** [comment]
Mold weight:

                                             Green <3000 pounds
                                             Red >3000 pounds
Also, there are few data shown in red - are they based on a condition? NO

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
