### ISSUE TITLE
mold to be cleaned report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#154]
![capture](https://cloud.githubusercontent.com/assets/11412673/11600452/4922740c-9a92-11e5-9194-38061d8ef40e.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11600467/68586188-9a92-11e5-9175-f38b4e0562f4.JPG)

Note should be across bottom of page

**Comment by nishant-njs** [comment]
Fixed.
