### ISSUE TITLE
Mold removed form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#158]
Setup people are not inserting total number of shots, this was to be a required field.

**Comment by nishant-njs** [comment]
Mold end number was always set to be a required field. See attached screenshot.
![screenshot-1](https://cloud.githubusercontent.com/assets/7536874/11761343/15d0f6d8-a0e5-11e5-9412-7c481939f418.jpg)

Duplicate issue - Refer #156 for our explanation.
