### ISSUE TITLE
too many values incorrect

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#159]
![capture](https://cloud.githubusercontent.com/assets/11412673/11633370/84095ab4-9cd0-11e5-9c91-ead2e21250e0.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11633395/a432b574-9cd0-11e5-9e7e-3cf36a8f6bf0.JPG)

**Comment by nishant-njs** [comment]
Currently, the server is running MySQL 5.0.27 which has to be upgraded to 5.7. Since multiple applications are hosted on the server we would upgrade over Christmas/New Year break. This issue will get resolved after the upgrade.

**Comment by nishant-njs** [comment]
Issue resolved. MySQL upgraded during Christmas shutdown.
