### ISSUE TITLE
Report not sorted correctly

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#160]
![capture](https://cloud.githubusercontent.com/assets/11412673/11635680/e455a956-9cdd-11e5-99e0-dcdb8c6e6574.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11635703/fcbc981a-9cdd-11e5-84a8-b33e15119c77.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11635726/1b996538-9cde-11e5-8c67-0b656d45f26d.JPG)

**Comment by nishant-njs** [comment]
Fixed.
