### ISSUE TITLE
no values

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#161]
![capture](https://cloud.githubusercontent.com/assets/11412673/11636311/2c78830e-9ce1-11e5-935c-1fead86b788e.JPG)

![capture](https://cloud.githubusercontent.com/assets/11412673/11636289/0384f072-9ce1-11e5-9f18-aa07c110812a.JPG)

**Comment by nishant-njs** [comment]
Fixed.
