### ISSUE TITLE
Need names not numbers

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#163]
![capture](https://cloud.githubusercontent.com/assets/11412673/11636612/95a4f7da-9ce2-11e5-801b-9cab6c5357ae.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11636629/acbe5a88-9ce2-11e5-9da3-741aae25a19a.JPG)

**Comment by nishant-njs** [comment]
Fixed.

**Comment by philolsonjr** [comment]
Sorry my name is incorrect, review were that data is coming from. I did not create these.

**Comment by nishant-njs** [comment]
Not sure where is your name incorrect. Share screenshot.

Screenshots from database and report:
1)
![screenshot-1](https://cloud.githubusercontent.com/assets/7536874/11743438/782d483a-a02d-11e5-9927-03985725e993.jpg)

2)
![screenshot-2](https://cloud.githubusercontent.com/assets/7536874/11743445/7c674450-a02d-11e5-8689-3360882c0808.jpg)

**Comment by philolsonjr** [comment]
The data is who is logged on to the computer not the database. Please review.

**Comment by nishant-njs** [comment]
See email from Paul dated: 12/23/2015. Please set up individual accounts for all employees that need to use the Mold Maintenance application
