### ISSUE TITLE
missing data from this week

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#164]
![capture](https://cloud.githubusercontent.com/assets/11412673/11636830/b1d3ab30-9ce3-11e5-9b9a-f7681dbb6670.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11636840/c9624b44-9ce3-11e5-9316-3e2b8512fe3d.JPG)

**Comment by nishant-njs** [comment]
2015 mold change times query is not displaying December month records because the access query has below date criteria. 
...WHERE ((([Part Mold Core Assembly].[Part Number]) Is Not Null) AND ((Order.[Mold Change Date Completed])  Between #12/1/2014# And #12/1/2015#) ..

**Comment by philolsonjr** [comment]
The move to the new database is very late, so new queries are required for the 2016 data. I have sent an e-mail to Paul.

**Comment by nishant-njs** [comment]
Added 2016 reports over the break -
![screenshot](https://cloud.githubusercontent.com/assets/7536874/12086865/eabab210-b2f3-11e5-9afb-920ee2c22047.jpg)
