### ISSUE TITLE
Wording incorrect

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#165]
![capture](https://cloud.githubusercontent.com/assets/11412673/11637607/046c3ba6-9ce8-11e5-9018-29a445a2961c.JPG)

![capture](https://cloud.githubusercontent.com/assets/11412673/11637585/de3cae3e-9ce7-11e5-8c5c-30f608cce6a5.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11637600/f6e8267a-9ce7-11e5-99fa-ab2cdfc49626.JPG)

**Comment by nishant-njs** [comment]
Fixed.
