### ISSUE TITLE
ort does not print as a report but as individual reports.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#166]
![capture](https://cloud.githubusercontent.com/assets/11412673/11637647/35f98a7a-9ce8-11e5-9571-2e8b310cae0b.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11637664/47a02478-9ce8-11e5-926b-9f8a3c4314d4.JPG)

**Comment by nishant-njs** [comment]
Fixed.
