### ISSUE TITLE
Data does look correct

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#167]
![capture](https://cloud.githubusercontent.com/assets/11412673/11638013/3a408172-9cea-11e5-9991-c2638811ae2a.JPG)

![capture](https://cloud.githubusercontent.com/assets/11412673/11637985/2a1a2122-9cea-11e5-9048-23148ade57aa.JPG)

**Comment by nishant-njs** [comment]
What's the error? More information needed to resolve. The report doesn't work in the version of Access we have.
![screenshot](https://cloud.githubusercontent.com/assets/7536874/11777413/7af82dc0-a274-11e5-91e0-2b0f0928f836.jpg)

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/11844272/7bb2bff4-a3d3-11e5-822c-6aecbe66bfd6.JPG)


Report no longer has any data???

The report works, because we are using the new database and not the access version the data for a week ago does not exist. you have to go into the query and change the dates.

![capture](https://cloud.githubusercontent.com/assets/11412673/11844378/1c6fa682-a3d4-11e5-85cd-b338b6c9dd6f.JPG)

As shown above all setups have a team member 1, most will have a tem member 3 (this is who did the kitting) , but most will not have a team member 2 as we only use one person for almost all setups today. ( we went from 3 to 1 setup person ).

**Comment by nishant-njs** [comment]
Fixed.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/11935638/8b862f3e-a7ce-11e5-82eb-23be9b103154.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11935654/a6280e02-a7ce-11e5-9ff4-fdb0a2a628cd.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11935676/c3ab705e-a7ce-11e5-9ed6-90bc22efea3d.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11935706/ebdb7182-a7ce-11e5-9fbe-f234f974dca5.JPG)



Report is missing data, review the the screen shots above.

This data was one record in access why is changed in this database???

**Comment by nishant-njs** [comment]
Sorry - absolutely no idea what are you referring too-
1) Report is missing data, review the the screen shots above - what record is it missing
2) This data was one record in access why is changed in this database??? - please elaborate.

**Comment by philolsonjr** [comment]
None of this data is in access anymore, we are not using access.
Read your data:

![capture](https://cloud.githubusercontent.com/assets/11412673/11956257/8bf1aa9c-a87e-11e5-92ca-6fdbd3820bee.JPG)

![capture](https://cloud.githubusercontent.com/assets/11412673/11956296/c789c3b4-a87e-11e5-871d-ebf369ebb324.JPG)

![capture](https://cloud.githubusercontent.com/assets/11412673/11956324/fe6d146c-a87e-11e5-9b17-cd941a604f61.JPG)


You are missing who kitted the job. It shows on one report but not on this one.

The datya was entered in the acces database as mold setup engineer 3:

![capture](https://cloud.githubusercontent.com/assets/11412673/11956366/4b12c2ee-a87f-11e5-9529-5192e7d5b57a.JPG)

**Comment by nishant-njs** [comment]
You compared it with wrong record.Below is the correct one in the same report
![167](https://cloud.githubusercontent.com/assets/7536874/11981481/15b67640-a9c9-11e5-95f9-81946a1e2fe1.png)

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/12400771/c09d5e48-bde7-11e5-9bdf-e34167196bbc.JPG)
Lets try again, this is you report, The yellow circle shows the missing data  it should not be 0. As shown below the data should show Jonathan's number.

![capture](https://cloud.githubusercontent.com/assets/11412673/12400889/6f4d2ebe-bde8-11e5-8272-e83fd249e4fc.JPG)

Report should call team member 1 team member 2 team member 3, as shown above from access as mold setup engineer 1....

**Comment by nishant-njs** [comment]
Data is correct, we checked with order id. We believe it is compared with wrong record.There are multiple records in weekly setup results with same part number.
