### ISSUE TITLE
Move the following reports to Metrics page to reduce confusion.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#168]
![capture](https://cloud.githubusercontent.com/assets/11412673/11656815/1dabc9c0-9d7d-11e5-9b9a-2b23eec13abe.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11656831/393ca1fa-9d7d-11e5-83a4-62b7118dcfa1.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11656842/4e90b5d2-9d7d-11e5-8523-1b6d780d6384.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11656855/6904b6e8-9d7d-11e5-9f9d-1549dce23c0f.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11656868/812ce678-9d7d-11e5-851d-aa559ccaac22.JPG)

**Comment by nishant-njs** [comment]
Updated
