### ISSUE TITLE
Bad values, should not be negative.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#173]
![capture](https://cloud.githubusercontent.com/assets/11412673/11658329/a05cc798-9d87-11e5-8a99-25372f1b0e7d.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11658346/b6b78154-9d87-11e5-8aea-01ff6485043f.JPG)

**Comment by nishant-njs** [comment]
We matched the query in Access - got negative values as well. See attached screenshot -
![173](https://cloud.githubusercontent.com/assets/7536874/11777281/709e2790-a273-11e5-8b6f-e3219c56b107.jpg)
