### ISSUE TITLE
Reports provide NO data.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#174]
![capture](https://cloud.githubusercontent.com/assets/11412673/11686104/dd870fc2-9e43-11e5-9a59-0184b678793c.JPG)

**Comment by nishant-njs** [comment]
Fixed.

**Comment by philolsonjr** [comment]
Sorry not correct, should show second shift data,
![capture](https://cloud.githubusercontent.com/assets/11412673/11693902/063d70c2-9e6d-11e5-8e5d-fb794da75a36.JPG)

**Comment by nishant-njs** [comment]
Query "Daily Setup Hours Shift 1" and "Daily Setup Hours Shift 2" is exactly the same except shift number. See attached screenshot with old data:
![174](https://cloud.githubusercontent.com/assets/7536874/11777145/52983e80-a272-11e5-947e-5e30403b4c9f.jpg)

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/11811221/ded982e6-a2f9-11e5-9951-8021d91d38ad.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11811225/efe7cfb6-a2f9-11e5-868e-7dc72d08621e.JPG)


Report to show second shift work, it shows nothing. the shift one report should show shift one only. I know the reports are the same BUT they should reflect what is going on by shift and they are not in your database. Review the query and correct.

**Comment by nishant-njs** [comment]
Fixed

**Comment by philolsonjr** [comment]
Second shift value is not correct:

12-15-2015 1.9333
12-15-2015 1.1000
total 3.0333 report states 1.2667.

**Comment by nishant-njs** [comment]
Fixed.. Let us know in more detail, if you are still facing this issue.
