### ISSUE TITLE
Report shows wrong data, should be the correct shift based on employee number.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#175]
![capture](https://cloud.githubusercontent.com/assets/11412673/11687842/a0788f10-9e4e-11e5-8b85-6edee7e0edda.JPG)

![capture](https://cloud.githubusercontent.com/assets/11412673/11687829/8df13b12-9e4e-11e5-9c15-919edaa64abf.JPG)

**Comment by nishant-njs** [comment]
Not sure what the error is. Compared the query with access and it looks ok.

**Comment by philolsonjr** [comment]
You need to see who and then use correct shift no.

**Comment by nishant-njs** [comment]
"You need to see who and then use correct shift no." - When was this added? We reviewed the query multiple times and couldn't find anything related to Shift No in the version of Access we have. Kindly share the screenshot from the copy you have.

**Comment by philolsonjr** [comment]
This is the query that drives the report:
![capture](https://cloud.githubusercontent.com/assets/11412673/11843690/87b38e9e-a3d0-11e5-964a-92dad11f6b1e.JPG)


![capture](https://cloud.githubusercontent.com/assets/11412673/11843611/1b011c3a-a3d0-11e5-9a56-b859b121a852.JPG)

Field on form should be blank and a required field so that the correct information is entered. I cannot see the table data so I cannot trace a error.

![capture](https://cloud.githubusercontent.com/assets/11412673/11843795/1b9641ce-a3d1-11e5-82e3-0a4fdef3c0bc.JPG)



![capture](https://cloud.githubusercontent.com/assets/11412673/11843845/5095c6ec-a3d1-11e5-8cfa-99a301d42ce3.JPG)

**Comment by nishant-njs** [comment]
Sorry, still having trouble with this issue. We understand that "Shift Completed" is set in the screenshots above. However, where in the query below are you comparing shift to employee no? 
 
![screenshot-1](https://cloud.githubusercontent.com/assets/7536874/11926210/e9e810e6-a7e8-11e5-847f-b6f08adc3de9.jpg)
