### ISSUE TITLE
Difference between NameID and MrNameID

### ISSUE THREAD

**Issue by nishant-njs** [nishant-njs/mold_maintenance_db#178]
What's the difference between NameID and MrNameID?
![capture](https://cloud.githubusercontent.com/assets/7536874/11777994/abb1a150-a277-11e5-9c4c-a8499998c507.jpg)

**Comment by philolsonjr** [comment]
The difference is when the field is filled in. MRname is used to see who requested the setup to start. Review the forms and you will see when they are used.

**Comment by nishant-njs** [comment]
Yes, we could go through the entire application and find in which form you are storing NameID & MRNameID info. Instead, it would be simpler if you could share the form name knowing how big the application is. Hope you understand.

Also, are you storing who is logged into the computer in NameID and MRNameID - see screenshot - 1?

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/11844060/54a44ca8-a3d2-11e5-9a6e-cfa6184b9625.JPG)

As listed above: MRname is used to see who requested the setup to start. The form is machine ready for setup. The function looks at who is logged in to the computer, not the database.

**Comment by nishant-njs** [comment]
Noted.
