### ISSUE TITLE
setup report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#18]
![capture](https://cloud.githubusercontent.com/assets/11412673/7006362/263af6cc-dc46-11e4-9288-1d0d3c388364.PNG)
![capture1](https://cloud.githubusercontent.com/assets/11412673/7006411/8a15a71e-dc46-11e4-87d7-1083871ea310.PNG)
Format is incorrect, note remove excess lines , add date, fit to screen correctly update logo, etc.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
