### ISSUE TITLE
Report missing most data

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#184]
![capture](https://cloud.githubusercontent.com/assets/11412673/11811589/111059a4-a2fc-11e5-9e34-85e1e7b4f062.JPG)

![capture](https://cloud.githubusercontent.com/assets/11412673/11811583/fcd7d57a-a2fb-11e5-81ee-4300add57673.JPG)

**Comment by nishant-njs** [comment]
Fixed.
