### ISSUE TITLE
Report needs a check box or yes/no not 0,1.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#188]
![capture](https://cloud.githubusercontent.com/assets/11412673/11850004/80826260-a3f0-11e5-81aa-fcee9aa0b405.JPG)

![capture](https://cloud.githubusercontent.com/assets/11412673/11850046/ae639f46-a3f0-11e5-8e95-17f6f93f86e5.JPG)

**Comment by nishant-njs** [comment]
Fixed by displaying Yes/No.
