### ISSUE TITLE
mold setup sheet

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#19]
![capture2](https://cloud.githubusercontent.com/assets/11412673/7006743/24565d1c-dc49-11e4-8d27-e625b0de997a.PNG)
Setup request shows double on report

**Comment by nishant-njs** [comment]
It is showing duplicate records in MS access (See attached image). The duplicate record is generated in MS Access when we click end setup. Please review the query used in MS Access.

![duplicate_record](https://cloud.githubusercontent.com/assets/7536874/7115478/a5b86a72-e206-11e4-8cfa-477fc97aff73.jpg)

**Comment by philolsonjr** [comment]
The double line shows that the mold was not removed from the machine from the previous setup. So the setup guy made a mistake, thus he needs to go back and remove the old mold from the machine in the database.

**Comment by nishant-njs** [comment]
From your last comment, we are assuming we don't have to make any code changes since the setup guy will have to manually rectify his mistake. Please close the issue.
