### ISSUE TITLE
Correct report weekly setup review report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#190]
![capture](https://cloud.githubusercontent.com/assets/11412673/11850614/0f9dadda-a3f4-11e5-8cb9-604068ac11e5.JPG)

![image](https://cloud.githubusercontent.com/assets/11412673/11850627/2c365640-a3f4-11e5-93e5-60379d7143f1.png)

Time should be on one line, too hard to read.

**Comment by nishant-njs** [comment]
Fixed.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/11878004/9118e70c-a4b8-11e5-880e-6fc44ded27ce.JPG)


?????????

**Comment by nishant-njs** [comment]
Re-uploaded latest file on server with fixes.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/11879274/fbb24c14-a4bf-11e5-9919-723c445fbdff.JPG)


No changes still as before????

**Comment by nishant-njs** [comment]
Set style "no-wrap" for all the date field in "weekly setup review" report in Main and Metrics menus. Attached are screenshot from the server.
Weekly Setup Review - Main
![weekly_setup_review-main](https://cloud.githubusercontent.com/assets/7536874/11891153/c516e2a6-a581-11e5-91c9-f46deb4d136c.jpg)

Weekly Setup Review - Metrics
![weekly-setup-review-metrics](https://cloud.githubusercontent.com/assets/7536874/11891156/cbc53ea4-a581-11e5-94e8-0c67ea912e5d.jpg)

**Comment by philolsonjr** [comment]
Sorry, it does not work on our system.

![capture](https://cloud.githubusercontent.com/assets/11412673/11900265/6492385c-a56a-11e5-927c-f2268ef00a32.JPG)

**Comment by nishant-njs** [comment]
Try this:
1) Open the report and press F5 on keyboard a few times. This will ensure you have the latest file from server.
2) Increase the width and height of the page. 

After increasing the width and height:
![screenshot-2](https://cloud.githubusercontent.com/assets/7536874/11926638/6ac5faf4-a7ec-11e5-9294-bfdd65c4b0e8.jpg)

When we reduce the width and height:
![screenshot-1](https://cloud.githubusercontent.com/assets/7536874/11926526/996fbeea-a7eb-11e5-8006-a54415d1a024.jpg)

**Comment by nishant-njs** [comment]
See above comments. I am also guessing this is working now as you've uploaded a screenshot (your last comment) in Issue #194 in which all the dates are on one line.
