### ISSUE TITLE
Total not correct

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#194]
![capture](https://cloud.githubusercontent.com/assets/11412673/11934192/3aaad2c0-a7c6-11e5-94df-fd649b203a3d.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/11934203/5c18f00e-a7c6-11e5-85fb-7278de3d792e.JPG)

**Comment by nishant-njs** [comment]
Need more information to solve this. 
Application is showing the value returned by query ([Startup Issues].[Number of Shots). Can you let us know about the correct total for this case.

**Comment by nishant-njs** [comment]
Need more information to solve this.
Application is showing the value from query field ([Startup Issues].[Number of Shots). What should be the correct total for this case, please let us know on this.

**Comment by philolsonjr** [comment]
Look you take the ending shot, subtract the starting shot and you have the number of shots. So 2243-2181= 62 not 3.

**Comment by nishant-njs** [comment]
Fixed.
