### ISSUE TITLE
Tool Shop does not e-mail or notification of a new mer.

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#196]

**Comment by nishant-njs** [comment]
Can you please share screenshots of the feature from MS Access.

**Comment by philolsonjr** [comment]
No screen shots available. The system sent an e-mail to the tool shop that a new MER was created.

**Comment by nishant-njs** [comment]
Where in MS Access is this feature implemented - Can you guide me to the code or macro name? Screenshot would be very helpful.

**Comment by philolsonjr** [comment]
Private Sub Save_Record_Exit(Cancel As Integer)
 
On Error GoTo Err_MailSetupreport_Click
    DoCmd.OutputTo acOutputReport, "Tool Shop MER Request Report", acFormatRTF, "R:\Mold Maintenance Database\Tool Shop MER Request Report.rtf"
    DoCmd.SendObject acSendReport, "Tool Shop MER Request Report", acFormatRTF, "Erich.Baumann@sandc.com;Allen.DeRosa@sandc.com;Fausto.Bobadilla@sandc.com;John.Stinebring@sandc.com", "Phil.Olson@sandc.com", , "Updated Mold Repair Report", , False

Exit_MailSetupreport_Click:
    Exit Sub

Err_MailSetupreport_Click:
    MsgBox Err.Description
    Resume Exit_MailSetupreport_Click
    
 
End Sub
![capture](https://cloud.githubusercontent.com/assets/11412673/12454556/a641c206-bf5d-11e5-8a76-58e67f79107d.JPG)
