### ISSUE TITLE
Transition from Year 2015 to 2016

### ISSUE THREAD

**Issue by nishant-njs** [nishant-njs/mold_maintenance_db#197]
Do we change the date from 2015-1-1 to 2016-1-1 in WHERE condition?
Here are the list of files:
metrics switchboard: query_lead_time_percent
metrics switchboard: query_lead_time_weekly_average
metrics switchboard: query_lead_time_weekly_average_2
metrics switchboard: query_lead_time_weekly_average_3
metrics switchboard: query_schedule_lead_time
metrics switchboard: query_scheduling_query
metrics switchboard: query_scheduling_query_2
metrics switchboard: query_scheduling_query_3
metrics switchboard: query_scheduling_query_4
metrics switchboard: query_scheduling_query_5
metrics switchboard: query_scheduling_query_6
metrics switchboard: query_setup_per_shift
metrics switchboard: query_shot_count
main switchboard: report_shot_count_results

**Comment by philolsonjr** [comment]
metrics switchboard: query_scheduling_query_3

**Comment by nishant-njs** [comment]
Updated query_scheduling_query_3. What about others?
