### ISSUE TITLE
setup schedule report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#20]
Job kitted field should be green when kitted, shows blank
![capture2](https://cloud.githubusercontent.com/assets/11412673/7006860/15563b42-dc4a-11e4-80b6-d1aea3df40e7.PNG)

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.

**Comment by philolsonjr** [comment]
not fixed.

**Comment by nishant-njs** [comment]
See attached screenshot..the kitting column in the report is updating. Please click "submit button" or "Save & Go To Mold Removal Form" after entering the kitting field.

![screenshot](https://cloud.githubusercontent.com/assets/7536874/7180183/e2b3f362-e45c-11e4-8553-502917b65a46.jpg)

![submit_btn](https://cloud.githubusercontent.com/assets/7536874/7180233/667ac018-e45d-11e4-8cc5-06780dd9531b.jpg)
