### ISSUE TITLE
Mold Setup Form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#201]
![capture1](https://cloud.githubusercontent.com/assets/11412673/12427504/524e9948-bea5-11e5-8817-361ecf5a17db.JPG)

Need to update mold setup form, If setup engineer 2 is not "open" then time applied is required field. Shop continues to for get to enter time, we have no way to go back and add.

![capture](https://cloud.githubusercontent.com/assets/11412673/12427561/94370160-bea5-11e5-8dd6-fde9b74e9923.JPG)

**Comment by nishant-njs** [comment]
Updated mold setup form - If setup engineer 2 and/or setup engineer 3 is not "open" then time applied is required field.
