### ISSUE TITLE
Last change created wrong data

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#208]
![capture1](https://cloud.githubusercontent.com/assets/11412673/12718181/5c3567d6-c8b2-11e5-877b-c72c1276e38b.JPG)
![capture](https://cloud.githubusercontent.com/assets/11412673/12718184/619c9ab4-c8b2-11e5-8a53-8a87a25a9ebd.JPG)

**Comment by philolsonjr** [comment]
Total labor time should only include Mold change time 1 and 2 as 3 is used for mold kitting and is not part of setup time.

**Comment by nishant-njs** [comment]
See the query from Access. Mold Change Time 3 is used to calculate reduction. What to do?

![change_time_reference](https://cloud.githubusercontent.com/assets/7536874/12945837/1f9e1910-d016-11e5-9fb8-cf563f2f9c33.png)

**Comment by philolsonjr** [comment]
After reviewing all the code I have no idea why the shop is putting time in the mold change time 3 position. The field is intended to identify who did the kitting and should not include a time value.
If you are not taking the value from kitting to mold change time 3, the shop is not entering the data correctly.
