### ISSUE TITLE
request setup to begin form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#21]
Form has wrong data:
![capture3](https://cloud.githubusercontent.com/assets/11412673/7006927/b793200a-dc4a-11e4-91b4-defe824ad34a.PNG)
![capture4](https://cloud.githubusercontent.com/assets/11412673/7006936/cf7e8c40-dc4a-11e4-857f-cd3da6aca996.PNG)

**Comment by nishant-njs** [comment]
Which data are you referring too? Is it Resource used - in this case can you enter new data and check?
