### ISSUE TITLE
mold setup schedule

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#22]
Machines state should be red background with the time in black once the machine is ready
![capture6](https://cloud.githubusercontent.com/assets/11412673/7006982/4098d0a2-dc4b-11e4-818c-2dd81919ea5d.PNG)

![capture5](https://cloud.githubusercontent.com/assets/11412673/7006972/2615c4ec-dc4b-11e4-89e5-59db2c636bf2.PNG)

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
