### ISSUE TITLE
setup schedule

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#25]
Machine state  for ea-1444 should be yellow when setup is completed, why is there three copies on the schedule
![capture9](https://cloud.githubusercontent.com/assets/11412673/7007176/e6f2720e-dc4c-11e4-9d36-da50305e4714.PNG)

**Comment by nishant-njs** [comment]
We double checked the code in access and web - they work the same way. I think the duplicate copies are because of old data. Can you enter new data, run the report and confirm.

**Comment by nishant-njs** [comment]
Issue already created refer - #19

**Comment by philolsonjr** [comment]
Problem is still active, multiple line appear on report for same request .

**Comment by nishant-njs** [comment]
"Problem is still active, multiple line appear on report for same request ." - Duplicate Issue - Refer #19. Please close this issue.
