### ISSUE TITLE
mold setup schedule

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#27]
report does not update to green in machine state when setup is completed.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7142684/ed7fb4ac-e29f-11e4-8f57-bdfda28ceb83.PNG)
Report turns red but started with 3 requests (should have been 1) not that it is closed four appear.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved. The reason there are 4 same rows is because of multiple clicks when creating a request. We have added a loading bar.

**Comment by nishant-njs** [comment]
See comment above. Please test and close the issue if resolved.
