### ISSUE TITLE
mold to be cleaned report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#39]
Report does not update when mold is set to "in process"

**Comment by nishant-njs** [comment]
Already working..please note all the report doesn't refresh automatically. You will have to refresh the webpage for now.

![1](https://cloud.githubusercontent.com/assets/7536874/7044687/cf2910f6-de13-11e4-94c8-bfe6ec35f7b9.jpg)

![2](https://cloud.githubusercontent.com/assets/7536874/7044688/d4d3403a-de13-11e4-804d-fff770127b97.jpg)

![3](https://cloud.githubusercontent.com/assets/7536874/7044689/d9c45b42-de13-11e4-8b5e-d9887c82f11e.jpg)

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7091446/4904e65a-df6f-11e4-9536-44bb71c40ad5.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7091461/644ec642-df6f-11e4-8800-06c2f5e2be37.PNG)
sorry does not work for me.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
