### ISSUE TITLE
edit core form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#40]
shows two no in basket fields
![capture](https://cloud.githubusercontent.com/assets/11412673/7008585/c7b54f94-dc59-11e4-8dce-e605b07454c3.PNG)
:

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.

![resolved](https://cloud.githubusercontent.com/assets/7536874/7044603/c4f240cc-de12-11e4-8c5b-55b13e9faf44.jpg)
