### ISSUE TITLE
core locations report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#41]
does not update as location is changed

**Comment by nishant-njs** [comment]
Already working..

![1](https://cloud.githubusercontent.com/assets/7536874/7044566/65c0b3ea-de12-11e4-8244-dcc111fd3804.jpg)

![2](https://cloud.githubusercontent.com/assets/7536874/7044569/6c14da1e-de12-11e4-968c-db3b5e687d0d.jpg)
