### ISSUE TITLE
Core location report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#42]
core to be listed by tool number not ID

**Comment by nishant-njs** [comment]
Not sure what you mean here. Compare the screenshots below:

![access](https://cloud.githubusercontent.com/assets/7536874/7044525/d0de3fcc-de11-11e4-8e3f-ef7f2af9c6af.jpg)

![web](https://cloud.githubusercontent.com/assets/7536874/7044527/db9e4b28-de11-11e4-8f70-a9f4f881690b.jpg)

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7091360/c4fad892-df6e-11e4-9de3-5941f2dfec66.PNG)
Should be by tool number, someone change ours(I will correct).

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
