### ISSUE TITLE
mold setup form report

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#46]
format needs adjusting, remove all the boxes, field missing setup goal
![capture](https://cloud.githubusercontent.com/assets/11412673/7009183/099133a2-dc5e-11e4-9eac-228a5340a273.PNG)

**Comment by nishant-njs** [comment]
Setup Goal field populated. Formatting will be done after fixing functionalities bugs.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
