### ISSUE TITLE
mold setup sheet - SELECT

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#47]
has no print button

**Comment by nishant-njs** [comment]
Are you referring to form or report? Please attached screenshot.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7091285/598092c8-df6e-11e4-9100-99065b320d38.PNG)
Used to print setup sheets, all for today, the one displayed, or a requested one.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
