### ISSUE TITLE
Close service request

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#49]
adjust time up or down not required when request is not a production stop

**Comment by nishant-njs** [comment]
We can turn off adjust time/date. However, in access it is possible to enter date/time even when production stop is not checked. Do confirm and we will update accordingly.

**Comment by philolsonjr** [comment]
The best way to do this is when Date Service completed is entered it should take the date and time and store it in the time up field, then if necessary they can modify.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved. Based on your comment above, we have updated Time Up field when "Date Service Completed" is entered.
