### ISSUE TITLE
Master form

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#54]
Master form does not fit on screen, must be rescaled to fit.

**Comment by nishant-njs** [comment]
Please attach a screenshot.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7252332/aa05e93a-e7f9-11e4-876d-9615909be639.PNG)

**Comment by nishant-njs** [comment]
Master form rescaled. Test and close the issue.
