### ISSUE TITLE
Request setup to begin

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#55]
Remove following fields: scheduled mold change date, resource used.
Operator field, remove "operator" and the name should be displayed not employee number.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7116349/9500f9c4-e1b6-11e4-83f8-d52b9237550d.PNG)
not fixed operator name was not corrected.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.

**Comment by philolsonjr** [comment]
![capture](https://cloud.githubusercontent.com/assets/11412673/7206907/465e5a58-e4fb-11e4-8759-d6873b7eb4af.PNG)
The word operator was not removed.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
