### ISSUE TITLE
Total Hours

### ISSUE THREAD

**Issue by nishant-njs** [nishant-njs/mold_maintenance_db#81]
In a few forms, there is a field called Total Hours which is a sum of the minutes entered by engineers. In MS Access, the sum is converted to Hours (see screenshot). You've opened issues (64, 72 etc.) which says it should display in minutes. Do you want us to display in minutes or hours and does it apply to all the forms?

![total-hours](https://cloud.githubusercontent.com/assets/7536874/7087797/b0155d9c-dfac-11e4-8d1d-afbab52ce472.jpg)

**Comment by philolsonjr** [comment]
It does not show a value on my screen.

**Comment by philolsonjr** [comment]
The value show be in hours but when a value is added the total does not update, in access it updates when the enter key is pressed.

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.
