### ISSUE TITLE
Notifications updated to include Picture

### ISSUE THREAD

**Issue by nishant-njs** [nishant-njs/mold_maintenance_db#83]
Created this issue from the e-mail sent by Phil Olson on April 16th. 

Please elaborate the feature in detail? Are you saving the picture location in database or uploading the actual picture in MS Access? What’s the refresh button doing? Lastly, where are the pictures displayed?

![screenshot](https://cloud.githubusercontent.com/assets/7536874/7228851/f9eb3786-e77a-11e4-9c01-5615bbd89a1d.jpg)

**Comment by philolsonjr** [comment]
Please read the standard work I sent you. It states that the files are saved to directory and displayed in the report.

**Comment by nishant-njs** [comment]
There are strict security restrictions when it comes to web pages. One of them is we cannot display the image located in the network. Technically, we have to upload the image to a folder on the server (happens in the background, user is not aware) and then display the image. User can still browse the image located in the network as in Access, only difference is they won’t see the network path. We need your approval before implementing this.

**Comment by philolsonjr** [comment]
We will need to update or change the picture when required.

**Comment by nishant-njs** [comment]
Feature added. Yes you will be able to update/change the picture when required. See screenshots below.
![1](https://cloud.githubusercontent.com/assets/7536874/8082531/8d50e9a6-0f9b-11e5-9046-498bf345ad83.jpg)

![2](https://cloud.githubusercontent.com/assets/7536874/8082534/92526f42-0f9b-11e5-89f0-468cb3f4381c.jpg)

**Comment by philolsonjr** [comment]
see #104

**Comment by nishant-njs** [comment]
#104 resolved. Please test and close the issue.
