### ISSUE TITLE
Mold removal from

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#91]
![capture](https://cloud.githubusercontent.com/assets/11412673/7236565/568860ce-e75b-11e4-95b6-aaab41c1360c.PNG)
Mold start number does not load

**Comment by nishant-njs** [comment]
Can you tell us where is "Mold Start Number" populating from? Is it from Orders Table? Also, on what conditions is Mold Start number populating from - is it combination of Order ID and Part Mold Core Assembly ID from Orders table?

**Comment by philolsonjr** [comment]
It comes from the order table, data was set when the mold was installed using form Mold setup and removal form.  


Mold Start Number.






![capture](https://cloud.githubusercontent.com/assets/11412673/7252692/f01cf1b8-e7fc-11e4-9d74-c1b809d7a772.PNG)

**Comment by nishant-njs** [comment]
Is "Mold Last Shot Number" mandatory field when End Set up is clicked?

**Comment by nishant-njs** [comment]
After troubleshooting, we found that the operator did not enter "Last Shot Number" before End Setup. We've added a validation now to avoid this in future. Please test and close the issue if resolved.

**Comment by philolsonjr** [comment]
Form never asked for last shot number, none entered, so problem is not fixed.

**Comment by nishant-njs** [comment]
Please close this issue. Refer Issue #100 which is related to Mold Last Shot number.
