### ISSUE TITLE
closed service request

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#97]
![capture](https://cloud.githubusercontent.com/assets/11412673/7237068/88e1ed30-e75e-11e4-8742-85a1678b361e.PNG)
Form will not close notes are fill in what is the issue?

**Comment by nishant-njs** [comment]
Updated. Please test and close the issue if resolved.

**Comment by philolsonjr** [comment]
Form does not work at all. No errors not closing.

**Comment by nishant-njs** [comment]
We tested extensively. Can you re-test on your end...if it errors out, please share the screenshot with the values entered.

**Comment by nishant-njs** [comment]
See my comment above - did the form error out? If so, can you share the screenshot with the values entered?

**Comment by philolsonjr** [comment]
Review the record file that I sent this morning. The file does not close and no errors are visible, I do not know what is wrong, but the file does not close. to keep returning this issue to me without fixing it is a waste of time.

**Comment by nishant-njs** [comment]
I have not received any record file in e-mail. Which file are you referring too?
