### ISSUE TITLE
Mold setup sheet for today

### ISSUE THREAD

**Issue by philolsonjr** [nishant-njs/mold_maintenance_db#99]
![capture](https://cloud.githubusercontent.com/assets/11412673/7252082/17476de6-e7f7-11e4-8c98-dc5d119c9fbc.PNG)
![capture](https://cloud.githubusercontent.com/assets/11412673/7252095/39c3e5ac-e7f7-11e4-9ccf-1d37bfb4f202.PNG)
Schedule and report do not match. Only setups schedule for TODAY should appear in report.

**Comment by nishant-njs** [comment]
This took us a while to figure out. We replicated the queries in MS Access. See attached screenshots from MS Access and let us know. The Part No (PA-7226) is not shown in "Daily Mold Setup Schedule" for date April 1 but is displayed in "Mold Setup Data Sheet" report. The queries shows the result of Setup Sheet today for date April 1. Please elaborate on your comment "Schedule and report do not match." above.

![99_screen1](https://cloud.githubusercontent.com/assets/7536874/7274788/812999ce-e91d-11e4-8d26-84b356190110.png)

![99_screen2](https://cloud.githubusercontent.com/assets/7536874/7274789/83fd3a5c-e91d-11e4-9598-c79113f16b88.png)

![99_screen3](https://cloud.githubusercontent.com/assets/7536874/7274791/8755b364-e91d-11e4-8915-2d7b9d03bff0.png)

**Comment by philolsonjr** [comment]
The report setup sheet today should include all part numbers scheduled for the day, as shown above the report has sda-1179 but it is not schedule. The report did not match what was scheduled. Note if the job was canceled it should not appear in the report.
